apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogapp-backend
  template:
    metadata:
      labels:
        app: blogapp-backend
    spec:
      containers:
        - name: backend
          image: 362231138751.dkr.ecr.us-east-1.amazonaws.com/blogapp-backend
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: "mongodb-service:27017"  # Service name of the MongoDB deployment

---

apiVersion: v1
kind: Service
metadata:
  name: blogapp-backend-service
spec:
  selector:
    app: blogapp-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP  # Change this if you are using a different type of service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP  # Change this if you need external access, e.g., LoadBalancer

